// packages/ui/src/groups/index.ts
// Barrel export for group UI components
export type { CreateGroupFormProps, CreateGroupFormData } from './CreateGroupForm'
export type { FederationStatusProps, FederatedConnection } from './FederationStatus'
export type { GroupCardProps } from './GroupCard'
export type { GroupEventsProps, GroupEvent } from './GroupEvents'
export type { GroupGrowthTrackerProps } from './GroupGrowthTracker'
export type { GroupListProps } from './GroupList'
export type { GroupProposalsProps, GroupProposalDisplay } from './GroupProposals'
export type { InvitationModalProps, InvitationData } from './InvitationModal'
export type { InviteButtonProps } from './InviteButton'
export type { InviteStatsProps } from './InviteStats'
export type { MemberDirectoryProps, Member } from './MemberDirectory'
export type { RoleAssignmentProps, GroupRole } from './RoleAssignment'
export { CreateGroupForm } from './CreateGroupForm'
export { FederationStatus } from './FederationStatus'
export { GroupCard } from './GroupCard'
export { GroupEvents } from './GroupEvents'
export { GroupGrowthTracker } from './GroupGrowthTracker'
export { GroupList } from './GroupList'
export { GroupProposals } from './GroupProposals'
export { InvitationModal } from './InvitationModal'
export { InviteButton } from './InviteButton'
export { InviteStats } from './InviteStats'
export { MemberDirectory } from './MemberDirectory'
export { RoleAssignment } from './RoleAssignment'
