export type { AllocationHistoryProps } from './AllocationHistory'
export { AllocationHistory } from './AllocationHistory'
export type { AllocationSliderProps } from './AllocationSlider'
export { AllocationSlider } from './AllocationSlider'
export type { ProposalAllocationWidgetProps } from './ProposalAllocationWidget'
export { ProposalAllocationWidget } from './ProposalAllocationWidget'
