// packages/ui/src/feed/index.ts
// Barrel export for feed UI components

export { PostCard } from './PostCard'
export { PostList } from './PostList'
export { PostComposer } from './PostComposer'
export { UrlPreviewCard } from './UrlPreviewCard'
export { ThreadView } from './ThreadView'
export { DuplicateThreadModal } from './DuplicateThreadModal'
export { PriorityList } from './PriorityList'
export { CommunityPrioritiesMap } from './CommunityPrioritiesMap'
export { RatingUI, RatingDisplay } from './RatingUI'
export { EvidenceAttachment } from './EvidenceAttachment'
export { EvidenceDisplay } from './EvidenceDisplay'
export { SentimentMap } from './SentimentMap'
export { TrendLines } from './TrendLines'
export { ActionRecommendations } from './ActionRecommendations'
export { InterestProfile } from './InterestProfile'
export { ProgressionIndicators } from './ProgressionIndicators'
export { BreadcrumbTrail, generatePipelineBreadcrumbs } from './BreadcrumbTrail'
export type { PostCardProps } from './PostCard'
export type { PostListProps } from './PostList'
export type { PostComposerProps, CreatePostData, TopicSuggestion } from './PostComposer'
export type { UrlPreviewCardProps } from './UrlPreviewCard'
export type { ThreadViewProps } from './ThreadView'
export type { DuplicateThreadModalProps, SimilarThread } from './DuplicateThreadModal'
export type { PriorityListProps } from './PriorityList'
export type { CommunityPrioritiesMapProps, CommunityPriorityStats } from './CommunityPrioritiesMap'
export type { TopicSentiment, SentimentMapProps } from './SentimentMap'
export type { SentimentDataPoint, TrendLinesProps } from './TrendLines'
export type { ActionRecommendation, ActionRecommendationsProps } from './ActionRecommendations'
export type { TopicInterest, InterestProfileProps } from './InterestProfile'
export type { ProgressionStage, ProgressionIndicatorsProps } from './ProgressionIndicators'
export type { BreadcrumbStep, BreadcrumbTrailProps } from './BreadcrumbTrail'
