// packages/ui/src/feed/index.ts
// Barrel export for feed UI components

export { PostCard } from './PostCard'
export { PostList } from './PostList'
export { PostComposer } from './PostComposer'
export { ThreadView } from './ThreadView'
export { DuplicateThreadModal } from './DuplicateThreadModal'
export { PriorityList } from './PriorityList'
export { CommunityPrioritiesMap } from './CommunityPrioritiesMap'
export { RatingUI, RatingDisplay } from './RatingUI'
export { EvidenceAttachment } from './EvidenceAttachment'
export { EvidenceDisplay } from './EvidenceDisplay'
export type { PostCardProps } from './PostCard'
export type { PostListProps } from './PostList'
export type { PostComposerProps, CreatePostData, TopicSuggestion } from './PostComposer'
export type { ThreadViewProps } from './ThreadView'
export type { DuplicateThreadModalProps, SimilarThread } from './DuplicateThreadModal'
export type { PriorityListProps } from './PriorityList'
export type { CommunityPrioritiesMapProps } from './CommunityPrioritiesMap'
