name: pr/proof-check

on:
  pull_request:

jobs:
  proof:
    name: pr/proof-check
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write  # needed to comment/label
    steps:
      - name: Check PR body for proof lines
        id: check
        uses: actions/github-script@v7
        with:
          script: |
            const body = (context.payload.pull_request.body || "");
            const required = ["VALIDATORS=GREEN", "LINT=OK"];
            const missing = required.filter(s => !body.includes(s));
            core.setOutput("missing", JSON.stringify(missing));

      # Comment & label if lines are missing
      - name: Comment & label if missing
        if: steps.check.outputs.missing != '[]'
        uses: actions/github-script@v7
        env:
          MISSING: ${{ steps.check.outputs.missing }}
        with:
          script: |
            const missing = JSON.parse(process.env.MISSING || "[]");
            const { owner, repo } = context.repo;
            const issue_number = context.payload.pull_request.number;

            const body = [
              "🔴 **REQUIRED:** Proof-lines missing in PR description.",
              "",
              "Please paste these two lines from CI logs:",
              "```",
              "VALIDATORS=GREEN",
              "LINT=OK",
              "```",
              "",
              "This check will fail until proof lines are added.",
              "Once added, re-run checks."
            ].join("\n");

            // Add comment
            await github.rest.issues.createComment({ owner, repo, issue_number, body });

            // Add a label (create if it doesn't exist)
            try {
              await github.rest.issues.addLabels({ owner, repo, issue_number, labels: ["needs-proof"] });
            } catch (e) {
              // ignore if labels not permitted or missing
            }

      # BLOCKING: Fail if proof lines are missing
      - name: Validate proof lines (REQUIRED)
        run: |
          MISSING='${{ steps.check.outputs.missing }}'
          if [ "$MISSING" != "[]" ]; then
            echo "::error::Proof lines missing from PR body: $MISSING"
            echo "PR body must include: VALIDATORS=GREEN and LINT=OK"
            exit 1
          fi
          echo "✅ Proof lines validated"
